// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	transaction "sirloinapi/features/transaction"

	mock "github.com/stretchr/testify/mock"
)

// TransactionData is an autogenerated mock type for the TransactionData type
type TransactionData struct {
	mock.Mock
}

// AddBuy provides a mock function with given fields: userId, uCart
func (_m *TransactionData) AddBuy(userId uint, uCart transaction.Cart) (transaction.Core, error) {
	ret := _m.Called(userId, uCart)

	var r0 transaction.Core
	if rf, ok := ret.Get(0).(func(uint, transaction.Cart) transaction.Core); ok {
		r0 = rf(userId, uCart)
	} else {
		r0 = ret.Get(0).(transaction.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, transaction.Cart) error); ok {
		r1 = rf(userId, uCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddSell provides a mock function with given fields: userId, uCart
func (_m *TransactionData) AddSell(userId uint, uCart transaction.Cart) (transaction.Core, error) {
	ret := _m.Called(userId, uCart)

	var r0 transaction.Core
	if rf, ok := ret.Get(0).(func(uint, transaction.Cart) transaction.Core); ok {
		r0 = rf(userId, uCart)
	} else {
		r0 = ret.Get(0).(transaction.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, transaction.Cart) error); ok {
		r1 = rf(userId, uCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionData interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionData creates a new instance of TransactionData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionData(t mockConstructorTestingTNewTransactionData) *TransactionData {
	mock := &TransactionData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
